### ISSUE TITLE
About Updater-old-release.json

### ISSUE THREAD

**Issue by AbdullahAlAsad** [Grace5921/OtaUpdater#5]
I am confused about the Updater-old-release.json file . 
why it is needed ? Does it needed for only showing the existing available rom for downloading or it is mutually important with Updater.xml ?

If I have only the Updater.xml is is it enough for the update checker dialogue to return true ?

what is the significance of "id" field in Updater-old-release.json ?

**Comment by androidlover5842** [comment]
it's needed to show your old builds or new builds in list and what ever id you use will be added before rom name so it will be easy for flasher to find it and updater.xml is to notify user if user has not installed new rom check wiki https://github.com/Grace5921/OtaUpdater/wiki
